export const prodcuts = [
  {
    _id: '1',
    name: 'Fila Kids Disruptor Ii Repeat Big Sneaker',
    image: '/images/p1.jpg', // 680 x 830
    description: 'best shoes',
    brand: 'Fila',
    category: 'Shoes',
    price: 99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: "PUMA Women's Tazon 5 Cross-Training Shoe",
    image: '/images/p2.jpg',
    description: 'best shoes',
    brand: 'PUMA',
    category: 'Shoes',
    price: 99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: "Under Armour Men's Sway Running Shoe",
    image: '/images/p3.jpg',
    description: 'best shoes',
    brand: 'Under Armour',
    category: 'Shoes',
    price: 99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: "New Balance Women's Fresh Foam 1165 V1 Walking Shoe",
    image: '/images/p4.jpg',
    description: 'best shoes',
    brand: 'New Balance',
    category: 'Shoes',
    price: 99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Converse Chuck Taylor All Star High Top Sneaker',
    image: '/images/p5.jpg',
    description: 'best shoes',
    brand: 'Converse',
    category: 'Shoes',
    price: 99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '6',
    name: "PUMA Men's Tazon 6 FM Running Shoe",
    image: '/images/p6.jpg',
    description: 'best shoes',
    brand: 'PUMA',
    category: 'Shoes',
    price: 99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];
